.TH whyami 6 2015-10-09

.SH NAME
\fBwhyami\fP \- ontological counterpart to \fBwhoami\fp that explains the meaning of life.

.SH SYNOPSIS
[\fB\-\-belief\fR]

.SH DESCRIPTION
\fBwhyami\fP is a humorous command that explains the meaning of life. It is intended
as a counterpart to the ubiquitous \fBwhoami\fp command.

.SH OPTIONS
.TP
.BR \-\-belief
Show the meaning of life according to the specific belief system

.SH SEE ALSO
\fBwhoami\fP(1)

.SH AUTHOR
\fBwhyami\fP was written by Jack Kingsman <jack.kingsman@gmail.com>. This manual was
written by Jack Kingsman <jack.kingsman@gmail.com> but may
be used by others under the same terms as \fBwhoami\fP itself.
